default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: tilfy-api_development

test:
  <<: *default
  database: tilfy-api_test

production:
  <<: *default
  database: tilfy-api_production
  username: tilfy-api
  password: <%= ENV['TILFY-API-V2_DATABASE_PASSWORD'] %>
